import pkgJSON from "../package.json";
import { MontereyVersion } from "./types";

/**
 * Cache for commonly accessed values to improve performance
 * @private
 */
const cache = {
    version: '',
    extension: '.monjson' as const,
    headerTemplate: '' as string
};

/**
 * Generates a standardized header comment for generated JavaScript files
 * @returns {string} Formatted header comment block
 */
export function getMontereyJavaScriptHeader(): string {
    if (!cache.headerTemplate) {
        cache.headerTemplate = `/*
 * Generated by Monterey.js ${getMontereyVersion()}
 * https://github.com/AbdullahCXD/monterey.js
 * 
 * Generation Time: ${new Date().toUTCString()}
 * 
 * This is an auto-generated file. Do not edit directly.
 */`;
    }
    return cache.headerTemplate;
}

/**
 * Returns the standard Monterey file extension
 * @returns {string} The Monterey file extension (.monjson)
 */
export function getMontereyExtension(): string {
    return cache.extension;
}

/**
 * Retrieves the current Monterey version
 * Uses cached version for better performance
 * @returns {string} Version string prefixed with 'v'
 */
export function getMontereyVersion(): MontereyVersion {
    if (!cache.version) {
        cache.version = pkgJSON.version.startsWith('v') ? 
            pkgJSON.version : 
            `v${pkgJSON.version}`;
    }
    return cache.version as MontereyVersion;
}

/**
 * Validates if a given filename has the correct Monterey extension
 * @param {string} filename - The filename to validate
 * @returns {boolean} True if the filename has valid Monterey extension
 */
export function isValidMontereyFile(filename: string): boolean {
    // Optimization: Early return for undefined/empty strings
    if (!filename) return false;
    return filename.toLowerCase().endsWith(cache.extension);
}

/**
 * Resets the internal cache
 * Useful for testing or when package version changes at runtime
 * @internal
 */
export function _resetHeadersCache(): void {
    cache.version = '';
    cache.headerTemplate = '';
}